version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    assignees:
      - soerenmartius
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
