<template>
  <div class="relative px-4 sm:px-6 lg:px-8">
    <div class="text-lg max-w-prose mx-auto mb-6">
      <h1
        class="
          mt-2
          mb-8
          text-3xl text-center
          leading-8
          font-extrabold
          tracking-tight
          text-gray-900
          sm:text-4xl sm:leading-10
        "
      >
        Privacy Policy
      </h1>
      <p class="text-xl text-gray-500 leading-8">
        Below Mineiros GmbH ("Mineiros" or "we") provides you with an overview
        of what personal data we process for what purpose and how we ensure the
        protection of that data. In section I. you can find information
        applicable in general. In section II. we explain the processing of
        personal data in the context of you visiting our websites
        (www.mineiros.io) ("Website"). Please read the following information
        regarding the privacy policy carefully. In case you have further
        questions, please do not hesitate to contact us at any time at
        <a href="mailto:datasecurity@mineiros.io">datasecurity@mineiros.io</a>.
      </p>
    </div>
    <div class="prose prose-lg text-gray-500 mx-auto">
      <h2>I. General Information</h2>
      <h3>
        1. Who is responsible for processing of personal data and whom you can
        approach
      </h3>
      <p>Controller of the processing of personal data is:</p>
      <p>
        Mineiros GmbH<br />Wilhelmine Gemberg Weg 13a, 10179 Berlin<br />Phone:
        <a href="tel:+49-151-407-669-46">+49 151 407 669 46</a><br />E-mail:
        <a href="mailto:hello@mineiros.io">hello@mineiros.io</a><br />Website:
        <a href="https://www.mineiros.io">https://www.mineiros.io</a>
      </p>
      <h3>2. How to reach our data protection officer</h3>
      <p>
        You can reach our data protection officer under the following contact
        information:
      </p>
      <p>
        Mineiros GmbH, Datenschutzbeauftragter, Wilhelmine Gemberg Weg 13a,
        10179 Berlin/Germany;
      </p>
      <p>
        E-Mail:
        <a href="mailto:datasecurity@mineiros.io">datasecurity@mineiros.io</a
        ><br />Phone: +49 151 407 669 46
      </p>
      <h3>3. What we process</h3>
      <p>
        We process personal data provided by you or generated by us. For further
        information, see section II.
      </p>
      <h3>
        4. For what purpose and on what legal basis do we process personal data
      </h3>
      <p>
        Generally, we process your personal data in accordance with the
        provisions of the European General Data Protection Regulation (GDPR) and
        the Federal Data Protection Act (BDSG) for various purposes. In
        principle, the following can be considered as the purposes of the
        processing: the processing for the initiation of contractual
        relationships and the performance of contracts (Art. 6 (1) lit. b GDPR),
        for the protection of legitimate interests (Article 6 (1) lit. f DSGVO),
        based on your consent (Article 6 (1) lit. a GDPR) and/ or statutory
        provisions (Art. 6 (1) lit. c GDPR).
      </p>
      <p>For further information, see section II.</p>
      <h3>5. Are you obligated to provide personal data</h3>
      <p>
        There is no legal or contractual obligation to provide us with personal
        data. We only ask you to provide us with the data necessary for our
        services. Without this personal data, we may not be able to offer you
        our services.
      </p>
      <h3>7. For how long do we process personal data</h3>
      <p>
        We process data only as long as it is necessary in relation to the
        initial specified, explicit and legitimate purpose.
      </p>
      <p>
        Additionally, we are subject to various filing and documentation
        obligations, including those arising from the German Commercial Code
        (HGB) and the German Tax Code (AO). The deadlines for storage and
        documentation specified there are up to ten years.
      </p>
      <p>
        In light of possible legal claims, the processing period is also
        determined by statutory time limitations, which can be up to thirty
        years according to §§ 195 ff. of the German Civil Code (BGB), whereby
        the regular time limitation is three years.
      </p>
      <h3>8. Your Rights</h3>
      <p>
        Every data subject has the right of access (Art. 15 GDPR), the right to
        rectification (Art. 16 GDPR), the right to erasure (Art. 17 GDPR), the
        right to restriction of processing (Art. 18 GDPR) and the right to data
        portability (Art. 20 GDPR). To exercise those rights, you can contact us
        under the contact information given in section I. 1. or 2.
      </p>
      <p>
        As far as the personal data is processed for the purpose of our
        legitimate interest according to Art. 6 (1) lit. f GDPR, you have the
        right to object according to Art. 21 GDPR. You can find further
        information regarding your right to object at the end of this Privacy
        Policy.
      </p>
      <p>
        In addition, if you are of the opinion that the processing of your
        personal data is unlawful, you have the right to lodge a complaint with
        the competent supervisory authority (Art. 77 GDPR). This right to
        complain is without any prejudice to any other administrative or
        judicial remedy. The competent supervisory authority for Mineiros is:
        Berliner Beauftragte für Datenschutz und Informationsfreiheit
      </p>
      <h3>9. External Links</h3>
      <p>On our Website we may link to other websites by third parties.</p>
      <p>
        Such websites by third parties are governed by the provisions and
        privacy policies of the respective third party offering the content
        behind those links. We do not actively check such links and external
        content unless required by applicable laws. If you discover wrong and/or
        inappropriate content please inform us, for example via email to
        hello@mineiros.io and we will delete and change such links immediately.
      </p>
      <h2>II. Processing of personal data regarding our Website</h2>
      <h3>1. Cookies&nbsp;</h3>
      <p>
        In order to offer you a convenient online service featuring numerous
        functions, our Website uses text files ("Cookies"). A cookie is a small
        file which asks permission to be placed on your computer’s hard drive.
        Once you agree, the file is added and the cookie helps analyze web
        traffic or lets you know when you visit a particular site. Cookies allow
        web applications to respond to you as an individual. The web application
        can tailor its operations to your needs, likes and dislikes by gathering
        and remembering information about your preferences.
      </p>
      <p>
        You can choose to accept or decline cookies. Most web browsers
        automatically accept cookies, but you can usually modify your browser
        setting to decline cookies if you prefer. This may prevent you from
        taking full advantage of our website.
      </p>
      <p>
        Processing of personal data through the use of cookies is based on
        Article 6 (1) lit. f GDPR. Purpose and our legitimate interest are
        improved functionality of our websites.
      </p>
      <h3>2. Access Data/ Server logfiles</h3>
      <p>
        We collect data about each visit of our Website (so-called server
        logfiles) ("Access Data"). Access Data includes the following: Name of
        the accessed website, file, date and time of access, amount of data
        transferred, notification of successful access, browser type and
        version, User's operating system, referrer URL (the previously visited
        page), IP address and the requesting provider.
      </p>
      <p>
        When using a mobile device Access Data also contains: Country code,
        language, device name, operating system and version name.
      </p>
      <p>
        We use this Access Data for statistical analysis for the purpose of
        operation, security and optimization of our Website. We anonymize Access
        Data before processing it for statistical analysis. However, we reserve
        the right to check these Access Data retrospectively if there is a
        justified suspicion of illegal use based on concrete indications. This
        data is stored because this is the only way to prevent the misuse of our
        Website and Software and, if necessary, allow us to investigate any
        potential crimes committed. As a matter of principle, this data will not
        be passed on to third parties unless there is a legal obligation to pass
        it on or the transfer of data serves criminal prosecution purposes.
      </p>
      <p>
        This data processing is based on Art. 6 (1) f. GDPR and we wish to
        achieve the legitimate interests of stabilizing and improving our
        Website, quality insurance and fraud prevention.
      </p>
      <h3>3. Google Analytics&nbsp;</h3>
      <p>
        Our website uses Google Analytics, a web analysis service provided by
        Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA
        (hereinafter referred to as "Google"). Google uses cookies and in this
        context creates pseudonymous user-profiles. The data created by the
        cookie is usually transferred to a server of Google in the USA and
        stored there. . Google complies with the privacy regulations of the
        EU-US Privacy Shield and is registered with the
        <a
          href="https://www.privacyshield.gov/participant?id=a2zt000000001L5AAI&amp;status=Active"
          >US Department of Commerce’s Privacy Shield Program</a
        >. Thus Google provides guarantees to comply with EU data protection
        law.
      </p>
      <p>
        In case the anonymization of IP-addresses is active on a website, the
        user’s IP-address will be truncated inside the European Union or the
        European Economic Area. Only in exceptional cases the user’s full
        IP-address will be transmitted to a server of Google in the US and
        truncated there. IP-anonymization is active on our websites.
      </p>
      <p>
        On behalf of us, Google will process this data in order to analyze your
        use of our websites, to generate reports on website activity and to
        render further services regarding the use of our websites. The
        IP-address transmitted by your browser will not be associated with other
        data in possession of Google.
      </p>
      <p>
        You can prevent the storage of cookies by modifying your browser setting
        to decline cookies. Furthermore, you can prevent the collection and
        following procession of data by Google through this cookie by
        downloading a browser-plugin through the following link:
        <a href="https://tools.google.com/dlpage/gaoptout/"
          >tools.google.com/dlpage/gaoptout/</a
        >.
      </p>
      <p>
        Preventing storage of cookies may prevent you from taking full advantage
        of our websites.
      </p>
      <p>
        You can find further information about terms and conditions as well as
        data protection on
        <a href="http://www.google.com/policies/privacy/"
          >www.google.com/policies/privacy/</a
        >.&nbsp;
      </p>
      <p>
        The processing of personal data through Google Analytics is based on
        Article 6 (1) lit. f GDPR. Purpose and our legitimate interest are
        analysis of the use of our websites as well as improved
        functionality.<br />
      </p>
      <h3>4. When subscribing to our newsletter</h3>
      <p>
        When you subscribe to our newsletter we process your email address based
        on your explicit consent Article 6 para. 1 subpar. 1 lit. a GDPR to
        provide you with regular information about us.<br />
      </p>
      <p>
        To send and personalize our newsletters, we use Mailchimp, a service by
        The Rocket Science Group, LLC, 675 Ponce de Leon Ave NE, Suite 5000,
        Atlanta, GA 30308 USA (Mailchimp).<br />
      </p>
      <p>
        Mailchimp enables us to measure and evaluate the behavior of our
        newsletter recipients. This includes the opening, click, bounce,
        delivery, unsubscription and conversion rates. This evaluation is
        carried out through pixel-tags, which collect information such as the IP
        address, browser type/version, email client and time of retrieval. In
        this way, it is also possible to track who opens the email and clicks on
        the links it contains. The evaluation of the user behaviour is carried
        out for the purpose of measuring the success of the email campaigns and
        improving our our offer.<br />
      </p>
      <p>
        The data you provide will be transferred to a Mailchimp server in the
        USA and stored there.<br />
      </p>
      <p>
        For more information about privacy related to Mailchimp, please refer to
        their
        <a href="https://mailchimp.com/legal/privacy/">Privacy Policy</a>.<br />
      </p>
      <p>
        The revocation of your consent is possible at any time, e.g. via a link
        at the end of each newsletter. Alternatively you can send us an email
        with your revocation request.<br />
      </p>
      <h3>5. When contacting us through the contact form</h3>
      <p>
        When contacting us (e.g. by email or through the website), we process
        your name, email address and any personal data disclosed in the message
        itself.
      </p>
      <p>
        The processing is based on Art. 6 (1) f. GDPR. Purpose and our
        legitimate interest is answering your enquiry and, if applicable,
        follow-up questions.<br />
      </p>
      <h3>6. Web analysis, Tracking and Targeting</h3>
      <p>
        The web analysis, tracking and targeting tools listed below are
        necessary for the purposes of our legitimate interests in accordance
        with Article 6 para. 1 subpar. 1 lit. f GDPR.<br />
      </p>
      <p>
        Through web analysis, we aim to ensure a needs-based design and the
        continuous optimisation of our website. At the same time web analysis
        enables us to statistically track the use of our website and evaluate it
        for the purposes of optimizing our offer for you.<br />
      </p>
      <p>
        Conversion tracking tools allow us to measure and analyse the
        effectiveness of certain measures on our website and on third-party
        platforms. We have a legitimate interest in making such measurements to
        target our customer communications. In this context, the user behaviour
        in connection with marketing measures are recorded and tracked, without
        disclosing the identity of the user tracked.<br />
      </p>
      <p>
        Through targeting tools we want to ensure that only certain advertising,
        based on your actual or assumed interests are displayed to you.<br />
      </p>
      <p>
        These interests are legitimate within the meaning of Article 6 para. 1
        subpar. 1 lit. f GDPR.<br />
      </p>
      <p>
        The respective catagories of data processed, specific purposes and
        specific options to opt-out can be found in the corresponding targeting
        tools, listed hereinafter.
      </p>
      <br />
      <h4>Google Analytics</h4>
      <p>
        Our website uses Google Analytics, a web analysis service provided by
        Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA
        (hereinafter referred to as "Google"). Google uses cookies and in this
        context creates pseudonymous user-profiles.<br />
      </p>
      <p>
        The information generated by the cookies about the use of our website
        (e.g. IP address of the accessing computer, time of access, referrer URL
        and information on the browser and operating system used) are generally
        transferred to servers of Google in the USA and processed there. Google
        complies with the privacy regulations of the EU-US Privacy Shield and is
        registered with the
        <a
          href="https://www.privacyshield.gov/participant?id=a2zt000000001L5AAI&amp;status=Active"
          >US Department of Commerce’s Privacy Shield Program</a
        >. Thus Google provides guarantees to comply with EU data protection
        law.<br />
      </p>
      <p>
        We use Google Analytics based on our legitimate interests (Art. 6 Para.
        1 Sentence 1 lit. f DSGVO) in the analysis and optimisation of our
        online services and the economic operation of this website. Google
        therefore processes the information on our behalf in order to evaluate
        the use of the website, compile reports on website activity and provide
        us with other services relating to website activity and internet usage
        for market research purposes and to tailor this website to meet our
        needs.<br />
      </p>
      <p>
        We have entered into a processor agreement with Google for the use of
        Google Analytics. Through this agreement, Google assures that it
        processes the data in accordance with the General Data Protection
        Regulation and guarantees the protection of the rights of the data
        subject.<br />
      </p>
      <p>
        We Google Analytics exclusively with IP anonymization enabled. This
        means that Google shortens the IP address of users within member states
        of the European Union or in other contracting states of the Agreement on
        the European Economic Area. Only in exceptional cases, the full IP
        address is transmitted to a Google server in the USA and shortened
        there. The IP address is, by no means, merged with other data held by
        Google.<br />
      </p>
      <p>
        We do not use the Universal Analytics with User ID offered by Google.<br />
      </p>
      <p>
        If necessary, the collected data will be transferred to third parties,
        if this is required by law or if third parties process the data on
        behalf of third parties.<br />
      </p>
      <p>
        The user data collected via cookies will be automatically deleted after
        14 months.<br />
      </p>
      <p>
        You can prevent the installation of cookies by setting the browser
        software accordingly. However, we would like to point out that in this
        case not all functions of this website can be used fully.<br />
      </p>
      <p>
        You can also prevent the collection of data generated by the cookie and
        relating to your use of the website (including your IP address) and the
        processing of this data by Google by downloading and installing a
        <a href="https://tools.google.com/dlpage/gaoptout?hl=en"
          >browser add-on</a
        >.<br />
      </p>
      <p>
        As an alternative to the browser add-on, especially for browsers on
        mobile devices, you can also prevent Google Analytics from capturing
        data by clicking on the following link.<br />
      </p>
      <h5>Analytics Opt-Out</h5>
      <p>
        An opt-out cookie will be set to prevent your data from being collected
        in the future when you visit this website. The opt-out cookie is only
        valid in this browser and only for our website and is stored on your
        device. If you delete the cookies in this browser, you must set the
        opt-out cookie again.<br />
      </p>
      <p>
        For more information about privacy in connection with Google Analytics,
        see the
        <a href="https://support.google.com/analytics/answer/6004245"
          >Google Analytics Help </a
        >. For information on Google’s use of data, please see
        <a href="https://policies.google.com/privacy?hl=en-US"
          >Google’s privacy policy.</a
        ><br />
      </p>
      <br />
      <h4>Google Ads</h4>
      <p>
        On our website we use Google Ads (Conversion Tracking and Remarketing)
        of Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA
        (hereinafter referred to as "Google"). The service enables us to design,
        statistically record, optimize and display advertising content according
        to our needs. In order to ensure the visibility of our offer, we are
        dependent on such advertising content. Google Ads places a cookie on
        your computer if you have accessed our website via a Google
        advertisement. These cookies lose their validity after 90 days. If you
        visit certain sections of our website and the cookie has not yet
        expired, Google may recognize that you have clicked on the ad and have
        been directed to that page.<br />
      </p>
      <p>
        In addition, we use remarketing pixels to collect and evaluate
        information about your use of our website. This enables us to address
        you on other websites with content relevant to you. According to Google,
        the data collected during remarketing is not merged with any personal
        data stored by Google. In addition, Google pseudonymises this data.
        Remarketing data based on tags are stored for 90 days.<br />
      </p>
      <p>
        The information generated by the cookie and pixel tag about your use of
        this website, such as click performance on texts and products or
        interactions with videos, are transmitted to a Google server in the USA
        and stored there. Google complies with the EU-US Privacy Shield
        regulations and is registered with the US Department of Commerce’s "US
        Privacy Shield" program.<br />
      </p>
      <p>
        Each ads customer receives a different cookie. As a result, cookies
        cannot be traced beyond the respective ads customer websites. The
        information collected using the conversion cookie is used to generate
        conversion statistics for ads customers who have opted for conversion
        tracking. As an ads customer, we see the total number of users who have
        clicked on an ad and been directed to a site with a conversion tracking
        tag. However, we do not receive any information that personally
        identifies you.<br />
      </p>
      <p>
        If you do not wish to participate in the tracking method, you can also
        decline to set a cookie as required for this – for example, by setting
        your browser to disable the automatic setting of cookies. You can also
        deactivate cookies for conversion tracking by setting your browser to
        block cookies from the domain "www.googleadservices.com". You can opt
        out to the use of the
        <a
          href="https://adssettings.google.com/authenticated?hl=en#display_optout"
          >remarketing pixel here</a
        >.<br />
      </p>
      ‍<br />
      <h4>Google Tag Manager</h4>
      <p>
        Our website uses the Google Tag Manager tool from Google LLC, 1600
        Amphitheatre Parkway, Mountain View, CA 94043, USA ("Google"). Google
        Tag Manager is used to manage the Google tools described in this privacy
        statement. For details regarding these tools, please refer to the
        information regarding the specific tool.<br />
      </p>
      <p>
        The Tag Manager tool itself (which implements the tags) is a cookie-free
        domain. The tool however, triggers other tags that may collect data.
        Google Tag Manager does not access this data. If a deactivation has been
        made at domain or cookie level, it will apply to all tracking tags
        implemented with Google Tag Manager.<br />
      </p>
      <p>
        For more information about Google Tag Manager, see the
        <a href="https://policies.google.com/privacy?hl=de&amp;gl=de"
          >terms of use for this product</a
        >.<br />
      </p>
      <p>
        <a href="https://policies.google.com/privacy?gl=de#products"
          >Google’s privacy policy</a
        >
        can be found here.
      </p>
      <br />
      <h4>LinkedIn Analytics and LinkedIn Ads</h4>
      <p>
        We use the marketing services "LinkedIn Ads" and "LinkedIn Analytics" of
        LinkedIn Ireland Unlimited Company, Wilton Place, Dublin 2, Ireland
        (hereinafter "Linkedin"). The service enables us to obtain statistical
        information about visitors to our website. This enables us to tailor and
        place our content and advertising to meet your needs. The following
        personal data is usually transmitted to a server in the USA through a
        pixel tag embedded in our website (so-called LinkedIn Insight Tag).<br />
      </p>
      <p>
        LinkedIn complies with the EU-US Privacy Shield and is registered with
        the US Department of Commerce’s US Privacy Shield Program.<br />
      </p>
      <p>
        The data processed using the embedded insight tag is stored in a cookie.
        The purpose of the cookie is to enable you to see relevant offers and
        recommendations that may be of interest to you after you have informed
        yourself on the website about certain services, information and
        offers.<br />
      </p>
      <p>
        You may opt out of LinkedIn’s analysis of your usage patterns and the
        display of interest-based recommendations
        <a
          href="https://www.linkedin.com/psettings/guest-controls/retargeting-opt-out"
          >here</a
        >.<br />
      </p>
      <h5>LinkedIn opt-Out</h5>
      <p>
        An opt-out cookie is set to prevent your information from being
        collected in the future when you visit this site. The opt-out cookie is
        only valid in this browser and only for our website and is stored on
        your device. If you delete the cookies in this browser, you must set the
        opt-out cookie again.<br />
      </p>
      <p>
        LinkedIn members can also edit their advertising preferences
        <a
          href="https://www.linkedin.com/psettings/advertising?trk=microsites-frontend_legal_cookie-policy"
          >here</a
        >. For more information about LinkedIn’s privacy practices, see the
        LinkedIn
        <a href="https://www.linkedin.com/legal/privacy-policy"
          >Privacy Policy</a
        >
        and LinkedIn
        <a href="https://www.linkedin.com/legal/cookie-policy">Cookie Policy</a
        >.<br />
      </p>
      <br />
      <h4>Your Data Subject Rights</h4>
      <p>You have the right, to<br /></p>
      <ul>
        <li>
          pursuant to Article 7 para. 3 of the GDPR, to revoke the consent you
          have given us at any time. As a consequence of this, we may no longer
          perform the data processing based on this consent in the future;
        </li>
        <li>
          pursuant to Article 15 of the GDPR, to obtain information about your
          personal data processed by us. In particular, you can request
          information about the purpose of processing, the category of the
          personal data, the categories of recipients, to whom your data were or
          will be disclosed, the planned duration of storing, the existence of a
          right to correction, erasure, restriction of processing or objection,
          existence of the right to complain, the origin of your data insofar as
          they were not collected by us, as well as the existence of automated
          decision making including profiling and if required, meaningful
          information relating to the details of this.
        </li>
        <li>
          pursuant to Article 16 of GDPR, to obtain immediate correction of
          incorrect data or the completion of your personal data which we have
          stored;
        </li>
        <li>
          pursuant to Article 17 of the GDPR, you may obtain the erasure of the
          personal data we have stored, where processing is not required for
          exercising the right of freedom of expression and information, for
          compliance with a legal obligation, for reasons of public interest,
          for the establishment, exercise or defence of legal claims;
        </li>
        <li>
          pursuant to Article 18 of the GDPR, to obtain the restriction of
          processing, where the accuracy of the personal data is contested by
          you, the processing is unlawful, however you oppose the erasure of the
          personal data, and we no longer need the data, however you require
          them for the establishment, exercise or defence of legal claims, or
          you have objected to the processing pursuant to Article 21 of the
          GDPR;
        </li>
        <li>
          pursuant to Article 20 of the GDPR, to receive the personal data you
          have provided to us in a structured, commonly used and
          machine-readable format, or to transmit those data to another
          controller;
        </li>
        <li>
          pursuant to Article 77 of the GDPR, to lodge a complaint to a
          supervisory authority. As a rule, you can contact the supervisory
          authority of your usual place of residence or work or our company
          headquarters.<br />
        </li>
      </ul>
      <h3>7. Data Subject rights management</h3>
      <p>
        We process your requests for information, correction, deletion,
        restriction of processing of personal data and data portability pursuant
        to the GDPR. In doing so we process the following personal data:
      </p>
      <ul>
        <li>Master data</li>
        <li>
          Privacy statements (consent to the processing of personal data,
          withdrawal of your consent, objections to the processing of personal
          data, statements asserting your rights of access, to rectification,
          erasure, restriction of processing, and data portability, including
          the information you provide us by asserting your rights)
        </li>
        <li>
          All data or categories of data that are the subject of the request.
        </li>
      </ul>
      <p>
        The processing of personal data is based on Article 6 (1) lit. c GDPR.
        Purpose is an effective affected rights management.
      </p>
      <h3>8. Automated decision-making and profiling</h3>
      <p>
        We do not use automated decision-making. Regarding profiling, we use the
        tracking tool Google Analytics. For further information about our use of
        Google Analytics see section II. 3. – "Google Analytics".
      </p>
      <h3>9. Who receives your personal data&nbsp;</h3>
      <p>
        We use processors (see Article 4 No. 8 GDPR) that process personal data
        on our behalf. These include the following processors:
      </p>
      <h4>
        Google Ireland Ltd., Gordon House, Barrow Street, Dublin, 4, Ireland
      </h4>
      <p>
        Data Processing Purpose: We use Google Analytics to analyze traffic on
        our Website.
      </p>
      <p>
        Data Processing outside the EU / Compliance with EU Data Protection
        Standard: Personal data is anonymized before being transferred outside
        of the EU/ EEA.
      </p>
      <p>
        Further Information: You can find further information here:
        <a href="http://www.google.com/policies/privacy/"
          >www.google.com/policies/privacy/</a
        >.
      </p>
      <h4>
        The Rocket Science Group, LLC, 675 Ponce de Leon Ave NE, Suite 5000
        Atlanta, GA 30308 USA&nbsp;
      </h4>
      <p>
        ‍Data Processing Purpose: Mailchimp, a service provided by The Rocket
        Science Group, LLC, enables us to measure and evaluate the behavior of
        our newsletter recipients. This includes the opening, click, bounce,
        delivery, unsubscription and conversion rates. This evaluation is
        carried out through pixel-tags, which collect information such as the IP
        address, browser type/version, email client and time of retrieval. In
        this way, it is also possible to track who opens the email and clicks on
        the links it contains. The evaluation of the user behaviour is carried
        out for the purpose of measuring the success of the email campaigns and
        improving our our offer. It cannot be ruled out that the information
        generated by the cookie about your use of this website is transmitted to
        and stored by a server of Mailchimp in the USA. Therefore, Mailchimp is
        certified under the terms of the EU-US Privacy Shield Framework, which
        ensures the security of your data.
      </p>
      <p>
        For more information on privacy at Mailchimp, please refer to their
        <a href="https://mailchimp.com/legal/privacy/">Privacy Policy.</a>
      </p>
      <h2>
        Information about your right to object in accordance with Art. 21
        General Data Protection Regulation (GDPR)
      </h2>
      <p>
        You have the right to object, on grounds relating to your particular
        situation, at any time to processing of personal data concerning you on
        the basis of Art. 6 (1) lit. f GDPR (processing of personal Data based
        on a balancing of interests); this includes profiling based on those
        provisions (Art. 4 No. 4 GDPR).
      </p>
      <p>
        Should you decide to object the processing, we will stop to process
        personal data concerning you, unless we can demonstrate compelling
        legitimate grounds for the processing which override your interests,
        rights and freedoms or the processing serves the purpose of
        establishment, exercise or defence of legal claims.
      </p>
      <p>
        You also have the right to object at any time to processing of personal
        data concerning you for the purpose of advertising; this also applies to
        profiling insofar as it is associated with advertising.
      </p>
      <p>
        Should you decide to object to the processing for advertising purposes,
        we will stop to process personal data concerning you for these purposes.
      </p>
      <p>
        The objection is not subject to any form. Ideally, it should be lodged
        at the bodies mentioned in section I. 1. and 2.
      </p>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'

export default Vue.extend({
  computed: {
    title: () => {
      return 'Mineiros - Privacy Policy'
    },
    description: () => {
      return 'The privacy policy of the Mineiros GmbH.'
    },
  },
  head() {
    return {
      meta: [
        {
          hid: 'title',
          name: 'title',
          content: this.title,
        },
        {
          hid: 'og:title',
          name: 'og:title',
          content: this.title,
        },
        {
          hid: 'description',
          name: 'description',
          content: this.description,
        },
        {
          hid: 'og:description',
          name: 'og:description',
          content: this.description,
        },
      ],
    }
  },
})
</script>

<style scoped>
a {
  @apply text-black;
}
</style>
